### ISSUE TITLE
Re-verify session

### ISSUE THREAD

**Issue by smessmer** [AscendingCreations/AxumSessionAuth#22]
I'm using [leptos_sse](https://docs.rs/leptos_sse/latest/leptos_sse/) after user login to generate a server-to-client stream that keeps pushing server side events to the client without the client having to explicitly poll them. Because there is no poll, there is also no call to axum that would re-verify that the user is still logged in. But once the user logs out (or a different user logs in), I would like the SSE stream to end.

Currently, I've added `AuthSession` as a parameter to the `handle_sse` function, but that means the user auth session is only checked once when the stream is established. Is there a way for me to re-verify the session? Something like `AuthSession::is_still_logged_in()`? Or maybe better something like `AuthSession::reverify()` that checks the session data again and updates `AuthSession::current_user` if necessary?

**Comment by genusistimelord** [comment]
hmm Well we would need to add this capability. I really need to understand all the different ways you might need to use This And axum_session so we can provide new functionality to both sides. Would be nice if you could make me a Minimal example of what all you are trying to accomplish so i could look at designing an API.

**Comment by smessmer** [comment]
Sure, thank you. Adding that API would be great. If there is a workaround I could use before it gets added, that would be useful to me too.

**Here is the use case:**
I have a database that contains a list of objects and I want clients to always know and display the current list of objects. Objects are bound to users, so each user has their independent list of objects. Server code can change the list and clients should be automatically updated. I'm using the reactive system of leptos to update the UI in clients automatically based on server events.

Let's assume the following API to read and write the list of objects:
```rust
pub struct Object(...);

lazy_static::lazy_static! {
    /// A trigger that gets called by code changing the list in the database
    /// For simplicity, we have a global trigger. Actual code will have per-user triggers here.
    pub static ref TRIGGER_LIST_UPDATED_EVENT: broadcast::Sender<()> = broadcast::Sender::new(10);
}

/// A function returning a list of objects, using a database query
pub async fn get_list(user: &User) -> Vec<Object> {
    call_db_and_return_list_of_objects(user).await
}

pub async fn add_to_list(user: &User, item: Object) {
   add_object_to_db(user, item).await;
   TRIGGER_LIST_UPDATED_EVENT.send(());
}
```

Now, whenever any server code modifies the list via `add_to_list`, it'll trigger `TRIGGER_LIST_UPDATED_EVENT`. That will in turn trigger a SSE event being sent to the client. The SSE function is an axum handler and looks like this:

```rust
pub async fn handle_sse(
        auth_session: AuthSession,
    ) -> Sse<impl Stream<Item = Result<Event, axum::BoxError>>> {
        let mut trigger_receiver = TRIGGER_LIST_UPDATED_EVENT.subscribe();

        let object_stream: AsyncStream<Result<Option<Vec<Object>>, axum::BoxError>, _> = stream! {
            // Yield once initially so the client gets an immediate value when the connection is established
            yield Ok(Some(get_list(auth_session.current_user).await));

            // After we sent the initial event, now we wait and each time `TRIGGER_LIST_UPDATED_EVENT` triggers,
            // we sent the updated list to the client.
            while let Ok(()) = trigger_receiver.recv().await {
                // Here, some time may have passed since the stream was initialized.
                // `auth_session` might be out of date and the user might be logged out, but we keep sending
                // them events.
                // This is what this PR is about. We need a way to get the current `auth_session.current_user`,
                // not the one that was present when the stream was initialized. So we need something like
                // auth_session.reverify() here to update `auth_session.current_user`.
                auth_session.reverify();
                yield Ok(Some(get_list(auth_session.current_user));
            }
        };

        let stream = ServerSentEvents::new("objects", object_stream).unwrap();
        Sse::new(stream).keep_alive(KeepAlive::default())
    }
```

The client can use these events using the leptos framework with a signal like this:
```rust
pub fn server_object_list() -> ReadSignal<Option<Vec<Object>>> {
    create_sse_signal::<Option<Vec<Object>>>("objects")
}
```

**Comment by smessmer** [comment]
Because there is no axum request involved when SSE updates trigger, there obviously is no access to cookies. So we likely won't be able to notice when a new user logged in. But I think we should be able to check on the server side whether the session is still valid and automatically stop the stream when a user logs out.

**Comment by genusistimelord** [comment]
does the client side connect as a web socket connection and send headers?

**Comment by smessmer** [comment]
This uses [leptos_sse](https://github.com/messense/leptos_sse), which uses HTTP SSE Events, not websockets. There is an alternative project, [leptos_server_signal](https://github.com/tqwewe/leptos_server_signal), which basically does the same thing but with websockets. I could switch to that if that makes it easier.

**Comment by smessmer** [comment]
IIUC, establishing the stream sends HTTP headers and I'm able to auth the user when establishing the stream, that part works correctly. The problem is just that the auth information isn't updated anymore while the stream is running and it just assumes that the user is still logged in and keeps sending updates to the client.

**Comment by genusistimelord** [comment]
im just trying to find out how this works So i know how Axum session and Axum auth need to function to work along side this.

for example we might need to make an Advanced API for both to bypass the service completely to allow you to do all the updates and control how long they need to stay alive etc. Also we need a way to verify the person still linked is still the person. Otherwise there is no point in doing what your doing if you can not somehow verify it is the same person. So I am wondering how the SSE thing talks to the Client side and so forth in order to maintain a proper connection.

**Comment by genusistimelord** [comment]
if you like it would be easier to talk on discord. you can find me on my discord channel.

**Comment by genusistimelord** [comment]
I have published new versions of AxumSession and AxumSessionAuth which include an advanced feature that unlocks some advanced functions. please give it a try.

**Comment by smessmer** [comment]
Thanks, that was quick. I tried to integrate it. Couple questions:
1. `is_logged_in` returns `AuthStatus` but that type does not seem to be re-exported. And the `session` module it's in is private. Can you export this somehow so I can match on the result of `is_logged_in`?
2. `is_logged_in` seems to return `LoggedOut` when the cache doesn't contain the user id, even if the session itself still has the user id. Can you explain the rationale behind that?
3. What is the use case for `reload_user`? I thought at first that it would reload and update the `current_user` field based on the current session, but seems it does not actually look at the session and just reloads the user based on the previous, possibly outdated, user id?

**Comment by genusistimelord** [comment]
Reload_user is when the user data is stale and needs reloading due to changes to the user data. It cant be done with the current held onto session otherwise. Also you would want it to use the current sessions user id and not any other as we did not verify those so we want to avoid them for Security reasons. I added a new function called sync_user_id which will update the users id to whatever the current sessions id is if it got changed.

is logged in i just pushed some changes to it. it is now public. Also it returns StaleUser now if the cache doesn't contain the user ID because if in cache mode they are considered stale if it got unloaded. The id itself is meaningless here unless in Non-cache mode. I added a check for if its in cache mode or not. if they are logged out but a ID exists then you can log them in forcefully via the reload_user.

**Comment by smessmer** [comment]
Cool, `sync_user_id` updates user id but not the user. Should we update that as well? Between `is_logged_in`, `reload_user`, `sync_user_id`, I'm getting confused as to which ones I need to call and in which order. I'm not confident that I'll get it right. Ideally, there'd be one function that does "the right thing" (TM) to update any user information from the auth session. Maybe something like the following, but as I said I'm not sure if I got it right:

```rust
/// Update the auth information from the session. This will yield an updated AuthSession object based on current session data.
pub fn sync_user(&mut self) {
    match self.is_logged_in() {
      AuthStatus::LoggedIn => (),
      AuthStatus::StaleUser => self.reload_user(),
      AuthStatus::DifferentID => {
        sync_user_id();
       // don't only sync user id, but also self.current_user
        sync_current_user();
      }
      AuthStatus::LoggedOut => {
        // not sure what to do here? It should set it to whatever the auth session would have been if it was created when the user wasn't logged in. Probably set current_user to None and userid to anonymous?
      }
    }
}
```

**Comment by genusistimelord** [comment]
use reload_user inplace of sync_current_user

if its logged_out it means there is no ID in the session so we need to Error and leave the stream.

**Comment by smessmer** [comment]
`sync_user_id` does also not correctly update the id if the session is expired, right?

The following does seem to work for me:
```rust
match auth_session.is_logged_in() {
    AuthStatus::LoggedIn => {}
    AuthStatus::StaleUser => {
        auth_session.reload_user().await;
    }
    AuthStatus::LoggedOut => {
        // End the stream
        return;
    }
    AuthStatus::DifferentID => {
        auth_session.sync_user_id();
        auth_session.reload_user().await;
    }
}
```

So I have something I can use now, thank you.

But I keep wondering if that's an API that's too easy to get wrong. I'd still prefer to just replace all of that with the much simpler:
```rust
auth_session.sync_user().await;
if auth_session.current_user().is_none() {
    // End the stream
    return;
}
```

Where `sync_user` could be implemented inside of `axum-session-auth`, with the following behavior:
```rust
pub async fn sync_user(&mut self) {
    self.id = // update user id from session
    self.current_user = // update current_user from self.id
}
```

The code doing that in the first place seems to live here: https://github.com/AscendingCreations/AxumSessionAuth/blob/main/src/service.rs
Maybe we can just re-use that code extracting `id` and `current_user` from the session and put it in a shared location. Or if that doesn't work, another option might be to implement it separately, something like:

```rust
pub fn sync_user(&mut self) {
    self.sync_user_id();
    self.reload_user();
}

// This requires changing the implementation of sync_user_id to set it to anonymous if it's logged out:
if let Some(id) = self.session.get::<Type>(&self.config.session_id) {
    self.id = id.clone();
} else {
    self.id = Default::default();
}
```

**Comment by smessmer** [comment]
Independently from that, I just noticed that the `auth_session.login_user()` function calls `self.session.renew()` which seems to change the session id. But the `AuthSession` object in my stream would likely still have the old session id. Would that cause issues?

**Comment by genusistimelord** [comment]
correct. you should Login and then forward them to the Stream. dont login on the stream. 

Also AxumSession got its own Advanced API as well as you also might need to use those along side the auth stuff.

**Comment by genusistimelord** [comment]
have the changes fixed your issues?

**Comment by smessmer** [comment]
It mostly works, thank you. I can successfully keep a stream going if it was created after the login.

One part that does not work is to keep a stream going through a logout/login event, and automatically change it from a "logged out stream" to a "logged in stream". Even if it's the same session. The reason for this seems to be that logout/login renew the session id, which marks the old session id as invalid.

I'm not sure what the best way to solve that part is. I'm currently experimenting with getting the stream id before and after calling login and updating some internal data structures on my side, but haven't gotten far yet.

**Comment by genusistimelord** [comment]
well you should not be handling a stream across a logout event. Any stream should be reestablished upon a login, this is for security generally.  you can manually change the Session ID by using the Session ID session Key to change it. if you truly need this. But I advise against this unless its for account swapping and not a logout.

**Comment by smessmer** [comment]
That may be true for logout, but I don't see a reason to re-establish the stream for login. The problem I'm facing is that closing and re-establishing the stream takes a second and that delays an otherwise instant login that doesn't even require a page reload.

But I think we can close this issue. I'm close enough that I can probably make it work and I'll reopen an issue here if it doesn't work. Thanks for your help!

**Comment by genusistimelord** [comment]
it was for security reasons. you want to rotate keys when logging in or switching to Secure zones in a website. this helps prevents others from accessing your information and gain access to the accounts capabilities. due to this we implemented it by default. If you need or want to bypass this then you will need to use the session manually and add and remove the user id manually.
